import PDFDocument from 'pdfkit-standalone';
const C = { navy: '#123241', teal: '#087f76', muted: '#58717d', line: '#dce7ea', pale: '#eff7f5' };
const clean = s => String(s ?? 'TBC').replace(/[–—]/g, '-').replace(/→/g, '>').replace(/×/g, 'x').replace(/[^\x20-\x7e\n]/g, ' ');
const money = n => 'AED ' + Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export function pdfFilename(bid) { const name = String(bid.name || bid.scope?.project?.name || 'Project').normalize('NFKC').replace(/[<>:"/\\|?*\x00-\x1f]/g, '-').replace(/\s+/g, ' ').replace(/[. ]+$/g, '').slice(0, 100) || 'Project'; return `${name} - Ataa Proposal.pdf`; }
export function createProposalPDF(bid) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 44, bufferPages: true, info: { Title: `${bid.name} - Ataa Proposal`, Author: 'Ataa', Subject: 'Project solution, approval and audit record' } });
        const chunks = []; doc.on('data', c => chunks.push(c)); doc.on('end', () => resolve(new Blob(chunks, { type: "application/pdf" }))); doc.on('error', reject);
        let y = 80;
        const width = () => doc.page.width - 88, bottom = () => doc.page.height - 62;
        function top() { doc.font('Helvetica-Bold').fontSize(16).fillColor(C.teal).text('ataa.', 44, 29, { lineBreak: false }); doc.font('Helvetica').fontSize(8).fillColor(C.muted).text(clean(bid.name).slice(0, 75), 115, 34, { width: doc.page.width - 159, lineBreak: false }); doc.moveTo(44, 57).lineTo(doc.page.width - 44, 57).strokeColor(C.line).stroke(); y = 80; }
        top();
        function page(landscape = false) { doc.addPage({ size: 'A4', layout: landscape ? 'landscape' : 'portrait', margin: 44 }); top(); }
        function ensure(h) { if (y + h > bottom()) page(); }
        function heading(t) { ensure(50); doc.font('Helvetica-Bold').fontSize(21).fillColor(C.navy).text(clean(t), 44, y, { width: width() }); y += 38; }
        function paragraph(t, size = 10) { const text = clean(t); doc.font('Helvetica').fontSize(size); const h = doc.heightOfString(text, { width: width(), lineGap: 3 }); if (h > bottom() - 80) { for (const part of text.match(/.{1,700}(?:\s|$)/gs) || [text]) paragraph(part, size); return; } ensure(h + 12); doc.font('Helvetica').fontSize(size).fillColor(C.muted).text(text, 44, y, { width: width(), lineGap: 3 }); y += h + 12; }
        function line(label, value) { paragraph(`${label}: ${value ?? 'TBC'}`); }
        function wrap(t, w) { doc.font('Helvetica').fontSize(9); const lines = []; let current = ''; for (const word of clean(t).split(/\s+/)) { if (doc.widthOfString(current + (current ? ' ' : '') + word) <= w) { current += (current ? ' ' : '') + word; continue; } if (current) lines.push(current); current = ''; for (const char of word) { if (doc.widthOfString(current + char) > w) { lines.push(current); current = ''; } current += char; } } if (current) lines.push(current); return lines.length ? lines : ['']; }
        function table(headers, rows, fractions) { const widths = fractions.map(n => n * width()); function head() { ensure(34); let x = 44; doc.rect(44, y, width(), 27).fill(C.pale); headers.forEach((h, i) => { doc.font('Helvetica-Bold').fontSize(8).fillColor(C.teal).text(clean(h), x + 6, y + 9, { width: widths[i] - 12, lineBreak: false }); x += widths[i]; }); y += 27; } head(); for (const row of rows) { const cells = row.map((v, i) => wrap(v, widths[i] - 12)); let offset = 0; const count = Math.max(...cells.map(c => c.length)); while (offset < count) { if (bottom() - y < 30) { page(); head(); } const take = Math.min(count - offset, Math.floor((bottom() - y - 16) / 12)); const height = take * 12 + 16; let x = 44; cells.forEach((cell, i) => { doc.font('Helvetica').fontSize(9).fillColor(C.navy).text(cell.slice(offset, offset + take).join('\n'), x + 6, y + 8, { width: widths[i] - 12, lineGap: 1 }); x += widths[i]; }); doc.moveTo(44, y + height).lineTo(44 + width(), y + height).strokeColor(C.line).stroke(); y += height; offset += take; } } y += 16; }
        const scope = bid.scope || {}, results = bid.results || {};
        heading('Project proposal baseline');
        paragraph(bid.approval ? 'Human-reviewed project snapshot' : 'Draft project snapshot');
        table(['PROJECT DETAIL', 'VALUE'], [['Project', bid.name], ['Customer', scope.project?.customer || bid.customer], ['Scope project name', scope.project?.name], ['Country / industry', `${scope.project?.country || 'TBC'} / ${scope.project?.industry || 'TBC'}`], ['System / architecture', `${scope.system?.type || 'TBC'} / ${scope.system?.architecture || 'TBC'}`], ['Workflow', bid.workflow], ['Generation mode', bid.mode === 'demo' ? 'Demo - sample AI outputs' : 'Live AI - Azure'], ['Status', bid.status], ['Bid ID', bid.id], ['RFQ source', bid.document?.name], ['Delivery', scope.constraints?.delivery_weeks != null ? `${scope.constraints.delivery_weeks} weeks` : 'TBC'], ['Support', scope.constraints?.support_years != null ? `${scope.constraints.support_years} years` : 'TBC']], [.31, .69]);
        paragraph('Synthetic catalog prices and service rules. This is a proposal baseline, not a binding offer or a certified engineering design.');
        if (bid.baseline) { line('Selected historical reference', bid.baseline.name); paragraph('Historical quantities are retained. This is reference baseline approval, not a newly sized final solution.'); if (results.delta?.length) table(['DELTA', 'REFERENCE', 'CURRENT', 'CHANGE'], results.delta.map(d => [d.label, `${d.reference} ${d.unit}`, `${d.current ?? 'TBC'} ${d.unit}`, d.delta == null ? 'TBC' : `${d.delta > 0 ? '+' : ''}${d.delta} ${d.unit}`]), [.28, .24, .24, .24]); }
        page(); heading('Bill of materials');
        if (results.priced_bom?.length) { table(['COMPONENT / PART', 'QTY', 'UNIT VALUE', 'LINE VALUE'], results.priced_bom.map(i => [`${i.description}\n${i.part_number}`, i.quantity, money(i.unit_price), money(i.line_total)]), [.48, .08, .22, .22]); line('Total catalog reference value', money(results.priced_bom.reduce((s, i) => s + i.line_total, 0))); paragraph('Reference prices in AED. Excludes service pricing, tax, discounts and margins.'); heading('Selection basis'); table(['PART', 'REQUIREMENT / BASIS'], results.priced_bom.map(i => [i.part_number, `${(i.requirement_ids || []).join(', ')}. ${i.reason || ''} ${i.quantity_basis || ''}`]), [.26, .74]); } else paragraph('No bill of materials was generated for this bid.');
        const arch = results.architecture;
        if (arch?.nodes?.length) {
            // Paginated vector drawing: layers stay ordered; large layers split into rows.
            const ordered = [...arch.nodes].sort((a, b) => a.layer - b.layer); let batches = [], batch = [], rows = 0;
            for (const layer of [...new Set(ordered.map(n => n.layer))]) { const ns = ordered.filter(n => n.layer === layer); for (let i = 0; i < ns.length; i += 4) { if (rows === 5) { batches.push(batch); batch = []; rows = 0; } batch.push(ns.slice(i, i + 4)); rows++; } } if (batch.length) batches.push(batch);
            batches.forEach((groups, index) => {
                page(true); heading(`Plant architecture${batches.length > 1 ? ` (${index + 1}/${batches.length})` : ''}`); paragraph(arch.title || 'Logical plant architecture', 10); const positions = {}; const start = y + 6; const boxW = 166, boxH = 55, gapX = 20, rowH = 66;
                groups.forEach((row, ri) => { const left = (doc.page.width - (row.length * boxW + (row.length - 1) * gapX)) / 2; row.forEach((n, ci) => { positions[n.id] = { x: left + ci * (boxW + gapX), y: start + ri * rowH, n }; }); });
                for (const edge of arch.edges || []) { const a = positions[edge.source], b = positions[edge.target]; if (!a || !b) continue; const sx = a.x + boxW / 2, sy = a.y + boxH, tx = b.x + boxW / 2, ty = b.y; doc.moveTo(sx, sy).lineTo(sx, sy + 9).lineTo(tx, sy + 9).lineTo(tx, ty).strokeColor('#86aaa6').lineWidth(.7).stroke(); doc.moveTo(tx - 3, ty - 4).lineTo(tx, ty).lineTo(tx + 3, ty - 4).stroke(); }
                Object.values(positions).forEach(({ x, y: ny, n }) => { doc.roundedRect(x, ny, boxW, boxH, 6).fillAndStroke(n.type === 'external' ? '#eef2f6' : '#f4faf8', C.line); doc.font('Helvetica-Bold').fontSize(9).fillColor(C.navy).text(clean(n.label).slice(0, 65), x + 8, ny + 8, { width: boxW - 16, height: 26, align: 'center' }); doc.font('Helvetica').fontSize(8).fillColor(C.teal).text(`${clean(n.id)} | Qty ${n.quantity} | ${clean(n.bom_item_id || 'External')}`, x + 5, ny + 39, { width: boxW - 10, align: 'center', lineBreak: false }); });
                y = start + groups.length * rowH + 5; paragraph('Logical groupings only. Physical redundancy, ports and safety compliance require engineering review. Connections across diagram pages are listed in the connection schedule.', 8);
            });
            page(); heading('Architecture component details'); table(['NODE / BOM', 'COMPONENT / DESIGN BASIS'], arch.nodes.map(n => [`${n.id} / ${n.bom_item_id || 'External'}`, `${n.label} (quantity ${n.quantity}). ${n.reason}`]), [.25, .75]); heading('Connection schedule'); table(['FROM > TO', 'PROTOCOL / CONNECTION BASIS'], (arch.edges || []).map(e => [`${e.source} > ${e.target}`, `${e.protocol || 'Protocol TBC'}. ${e.label || ''}. ${e.basis || ''}`]), [.25, .75]);
        } else { page(); heading('Plant architecture'); paragraph('No new plant architecture was generated for this reference-selection workflow. The selected historical BOM is included above; a new solution design remains required.'); }
        page(); heading('Service hours'); const services = results.services;
        if (services) { table(['ACTIVITY / RULE', 'CALCULATION', 'HOURS'], services.lines.map(l => [`${l.activity} / ${l.id}`, l.calculation, l.hours]), [.48, .36, .16]); line('Calculated effort subtotal', `${services.total_hours} hours`); line('Estimate status', services.status); for (const u of services.unresolved || []) paragraph(`EXCLUDED: ${u.activity}. ${u.reason}`); for (const n of services.notes || []) paragraph(n); paragraph('Hours are calculated from synthetic rules. Unresolved services are excluded from this subtotal.'); } else paragraph('No new service estimate was generated for this reference-selection workflow.');
        page(); heading('Requirements and review items'); table(['ID / PRIORITY', 'REQUIREMENT / SOURCE'], (scope.requirements || []).map(r => [`${r.id} / ${r.mandatory ? 'Mandatory' : 'Preferred'}`, `${r.text}\nSource: ${r.source}`]), [.25, .75]);
        heading('Clarifications'); for (const c of scope.clarifications || []) paragraph(`${c.id} [${c.severity}] ${c.resolved ? 'Resolved' : 'Open'}: ${c.question}\nAnswer: ${c.answer || 'Not recorded'}`);
        heading('Assumptions and gaps'); const notes = [...(scope.assumptions || []), ...(results.bom?.assumptions || []), ...(arch?.assumptions || []), ...(arch?.issues || []), ...(results.bom?.gaps || []).map(g => `${g.requirement_id}: ${g.reason}`)]; if (!notes.length) paragraph('None recorded.'); for (const n of notes) paragraph(n);
        page(); heading('Human approval'); if (bid.approval) { line('Approval type', bid.approval.type); line('Reviewer', bid.approval.reviewer); line('Recorded at', bid.approval.at); line('Decision', bid.approval.conditional ? 'Approved with conditions' : 'Approved'); paragraph('Decision notes: ' + (bid.approval.notes || 'None recorded.')); } else paragraph('Not yet approved.'); paragraph('Local prototype: reviewer identity is self-attested, not an authenticated digital signature.');
        heading('Audit trail'); table(['TIME (UTC)', 'ACTION / DETAIL'], (bid.audit || []).map(a => [a.at, `${a.action}\n${a.detail}`]), [.29, .71]);
        const range = doc.bufferedPageRange(); for (let i = 0; i < range.count; i++) { doc.switchToPage(i); doc.font('Helvetica').fontSize(8).fillColor(C.muted).text(`Ataa | ${bid.mode === 'demo' ? 'Demo sample' : 'Live AI'} | ${bid.approval ? 'Reviewed snapshot' : 'Draft'}`, 44, doc.page.height - 34, { lineBreak: false }); doc.text(`${i + 1} / ${range.count}`, doc.page.width - 95, doc.page.height - 34, { lineBreak: false }); } doc.end();
    });
}
